### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [werewolfe/f1-3-c2p1-colmar-academy#5]
Satisfactory 👍 

Awesome job organizing your project repository, your code is concise and easy to read as well. And, of course, you did a great job writing a mobile responsive website!

Just for practice you should see if you can make some nice mobile versions of your previous sites. There's no reason you shouldn't leave this program without a full portfolio of mobile responsive websites!

**Comment by werewolfe** [comment]
Thanks for your time, suggestions and comments @stevetoro ! I appreciate it big time.
